version: '3.8'

services:
  api:
    build: .
    restart: always
    command: uvicorn app:app --reload --host 0.0.0.0 && 
             alembic revision --autogenerate && 
             alembic upgrade head
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=''
      - POSTGRES_PASSWORD=''
      - POSTGRES_DB=''
      - POSTGRES_HOST=db
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=''
      - POSTGRES_PASSWORD=''
      - POSTGRES_DB=''