"""empty message

Revision ID: 17cf9900c260
Revises: 
Create Date: 2023-02-16 17:58:25.473629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cf9900c260'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('job_position', sa.String(), nullable=True),
    sa.Column('credit_sum', sa.String(), nullable=True),
    sa.Column('credit_month', sa.Integer(), nullable=True),
    sa.Column('tariff_id', sa.Float(), nullable=True),
    sa.Column('score_shk', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('living_region', sa.String(), nullable=True),
    sa.Column('monthly_income', sa.Float(), nullable=True),
    sa.Column('credit_count', sa.Float(), nullable=True),
    sa.Column('overdue_credit_count', sa.Float(), nullable=True),
    sa.Column('open_account_flg', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
